### ISSUE TITLE
reorganize files

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-mem#89]
replace "assim" with asym

replace "data_in/out" with "w/r_data"

verify the consistency of directory names, file names and module names

reg_file means sp_reg_file effect the change 

what is the difference between the _big files and the one without this suffix?
replace with w_wide_r_narrow and  w_narrow_r_wide

each terminal directory should contain 2 files: x, x_tb.v

write a top Makefile that simulates any memory module with icarus and opens gtkwave in background

make PATH=path/to/module/dir

etc

**Comment by jjts** [comment]
also mv mem related python scripts from iob-soc to software/python

**Comment by JDLopes** [comment]
- [X] replace "assim" with asym

- [ ] replace "data_in/out" with "w/r_data"

- [/]  verify the consistency of directory names, file names and module names

- [X]  reg_file means sp_reg_file effect the change

- [ ] what is the difference between the _big files and the one without this suffix? replace with w_wide_r_narrow and w_narrow_r_wide

- [/]  each terminal directory should contain 2 files: x, x_tb.v

- [ ]  write a top Makefile that simulates any memory module with icarus and opens gtkwave in background

- [ ]  make PATH=path/to/module/dir

 etc

**Comment by jjts** [comment]
PATH is a bad name as it is a system variable
MODULE_DIR is better

**Comment by jjts** [comment]
check box is nice

**Comment by jjts** [comment]
All done!
